# Generated by Django 3.1.5 on 2021-02-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('username', models.CharField(max_length=50)),
                ('noofpets', models.IntegerField()),
                ('noofdays', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
