# Generated by Django 3.1.5 on 2021-02-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsomeapp', '0002_plist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ppList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('brand', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
