# Generated by Django 3.1.5 on 2021-02-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsomeapp', '0004_daycare'),
    ]

    operations = [
        migrations.CreateModel(
            name='caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('location', models.CharField(max_length=100)),
                ('adds', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
