# Generated by Django 3.1.5 on 2021-03-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsomeapp', '0010_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plist',
            name='petbreederemail',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='plist',
            name='petbreederimg',
            field=models.ImageField(default='', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='plist',
            name='petbreederlocation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plist',
            name='petbreedername',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plist',
            name='petbreederoffer',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plist',
            name='petbreederphone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='plist',
            name='petbreederstatus',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
