# Generated by Django 3.1.5 on 2021-03-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsomeapp', '0011_auto_20210312_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='vet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('phone', models.CharField(default='', max_length=12)),
                ('email', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
