# Generated by Django 3.1.5 on 2021-04-03 10:43

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsomeapp', '0014_caretaker_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='caretaker',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='caretaker',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
