# Generated by Django 3.1.5 on 2021-04-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsomeapp', '0015_auto_20210403_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
