# Generated by Django 3.1.5 on 2021-04-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsomeapp', '0016_caretaker_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
