# Generated by Django 3.1.5 on 2021-04-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsomeapp', '0017_auto_20210403_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='contact',
            field=models.CharField(default='', max_length=12),
        ),
    ]
