# Generated by Django 3.1.5 on 2021-04-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsomeapp', '0020_auto_20210403_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=70)),
                ('message', models.CharField(max_length=5000)),
                ('to_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
